
remote_theme: #mmistakes/so-simple-theme

locale: en-US
title: "Hi B0HO"
description: "A simple Jekyll theme for words and pictures."
baseurl: 
url: "https://b0ho.github.io"
logo: "/images/so-simple-site-logo.png"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: # 200
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: "UA-2011187-2"
disqus:
  shortname: "b0ho"
google_site_verification: "UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_portfolio"
      type: portfolio
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: b0ho
  picture: /images/b0ho.jpg
  email:
  links:
    - title: Instagram
      url: https://instagram.com/b0ho
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/b0ho
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Instagram
    url: https://instagram.com/b0ho
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/b0ho
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
